security:
  basic:
    enabled: false

management:
  security:
    enabled: false

spring:
  profiles:
    cloud
  datasource:
    driverClassName:
      com.mysql.jdbc.Driver
    url:
      ${vcap.services.mysql.credentials.jdbcUrl}
